services:
  php-fpm:
    container_name: php-fpm
    image: cyberduck/php-fpm-laravel:8.3
    volumes:
      - .:/var/www
    links:
      - mysql
    depends_on:
      - mysql

  nginx:
    image: nginx
    ports:
      - "8888:80"
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  mysql:
    image: mysql
    restart: always
    volumes:
      - .docker/mysql_data:/var/lib/mysql
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
      MYSQL_USER: todolist
      MYSQL_PASSWORD: todolist